services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8500
      - TORRENTING_PORT=6888
    volumes:
      - /data/disk2t/qbittorrent:/config
      - /data/downloads:/downloads
    ports:
      - 8500:8500
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped

