services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8600
      - TORRENTING_PORT=6888
    volumes:
      - /data/disk2t/qbittorrent/appdata:/config
      - /data/downloads:/downloads
    ports:
      - 8600:8600
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped

